### ISSUE TITLE
I have a question. Thank you for your help

### ISSUE THREAD

**Issue by xinlian4499** [ManeeshaPerera/solar-forecasting-framework#1]
I am running the code for the paper titled as "Multi-Resolution, Multi-Horizon Distributed Solar PV Power Forecasting with Forecast Combinations" meet a question. There is an error reported—— ValueError : not enough values to unpack (expected 2, got 1).I am unable to solve this problem. Please help me, thank you.

**Comment by xinlian4499** [comment]
That‘s all.
Traceback (most recent call last):
  File "D:\project\solar-forecasting-framework-master\main.py", line 35, in <module>
    forecasts_combinations = fc_approach(data, horizon)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\solar-forecasting-framework-master\forecast_combinations_approach.py", line 35, in run_forecast_combinations_approach
    test_fc = base_learners.run_base_models(horizon, train, test, external_train, external_test)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\solar-forecasting-framework-master\run_base_models.py", line 50, in run_base_models
    arima.find_arima_params()
  File "D:\project\solar-forecasting-framework-master\tsmodels\autoregressive.py", line 33, in find_arima_params
    model.fit(self.train_data.iloc[:, 0], exogenous=self.train_features)
  File "D:\anaconda3\envs\jfcpytorch\Lib\site-packages\pmdarima\pipeline.py", line 202, in fit
    named_kwargs = self._get_kwargs(**fit_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\jfcpytorch\Lib\site-packages\pmdarima\pipeline.py", line 139, in _get_kwargs
    step, param = pname.split('__', 1)
    ^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by lalalalus** [comment]
i have the same question.but i change the version like the requirement.txt say .And it successfuly work.
